version: '3'
services:
  dev:
    build: .
    command: bash -c "yarn && yarn dev"
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    working_dir: /usr/app
    ports:
      - '3030:3030'
